---
ID: "fff79fc9-22bc-4013-afac-9217b38afbf8"
Parent: "6c99bb3a-cd63-48bd-8368-38e253da0d3b"
Template: "f62b4cd7-754c-4461-810f-2b6bd2c92a0d"
Path: /sitecore/client/Applications/ExperienceProfile/Contact/PageSettings/Tabs/Activity/Activity Subtabs/Automations
DB: core
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
- ID: "deab3795-056f-4421-adf0-758844461b72"
  Hint: Placeholder Name
  Value: Automations
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          id="{7717EB6C-9F90-4C58-826D-5E87722A0318}"
          par="Id=AutomationsTabId&amp;IsVisible=False&amp;Text=%7bFFF79FC9-22BC-4013-AFAC-9217B38AFBF8%7d"
          uid="{BD91234B-D6BF-4F13-A570-9DB63DEDBA24}" />
        <r
          id="{F6C9F461-FCAF-47DC-AA01-C8C64C2EFFB8}"
          par="Id=AutomationsTabBorder"
          uid="{503FB313-E0E0-483C-9CA2-AD0B35800B75}" />
        <r
          id="{FD97BD6A-2C46-4EB9-9F1F-7A2D7249DCC5}"
          par="Database=core&amp;Id=AutomationsLoadOnDemandPanel&amp;ItemId=%7b5BD8A11C-A7EE-4471-98F3-E6FFBE926968%7d"
          ph="AutomationsTabBorder.Content"
          uid="{4BCF3201-4F40-4DB1-93A6-0A048E4D6DB4}" />
        <r
          id="{F517C5E4-9A53-46C3-B922-5B44E6DAAA48}"
          par="Id=AutomationsIndicatorImage&amp;IsVisible=%7bBinding+AutomationsLoadOnDemandPanel.isLoaded%2c+Converter%3dNot%7d&amp;Width=60px&amp;Height=60px"
          ph="AutomationsTabBorder.Content"
          uid="{AB94FCCC-9FAB-4B95-A2DE-8E692EC8A865}" />
        <r
          ds="{88134D50-FA78-406D-8C52-8286EB12BB25}"
          id="{FE9723FC-56E4-4CA8-9C64-CB34F29462A5}"
          par="Id=AutomationsProgressIndicator&amp;IsBusy=%7bBinding+AutomationsLoadOnDemandPanel.isBusy%7d&amp;TargetControl=AutomationsTabBorder"
          ph="AutomationsTabBorder.Content"
          uid="{C89BB4F5-F40C-48E0-B0D8-1C9521F20EF6}" />
      </d>
    </r>
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Automatiseringer
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170113T074658Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Engagement Plans
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: "20140611T165156:635381023165699148"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Engagement plans
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140125T122705
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: オートメーション
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170113T075734Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
