---
ID: "c2d9b2bc-dc53-4e65-af1a-b902c1729a15"
Parent: "1375e1a2-c0f5-46bc-a9f5-dcad88ef4653"
Template: "1375e1a2-c0f5-46bc-a9f5-dcad88ef4653"
Path: /sitecore/templates/AI/AIHome/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{DD215D0D-94C7-459D-BCB3-A6F04CDB3F55}">
        <r
          id="{FB72BC38-B47D-4C35-9222-EAE0154F10C5}"
          ph="MainContent"
          uid="{502C6566-0DE3-4F2B-939D-12964A768E23}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170905T200426Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
